spring.application.name=web-app

spring.security.oauth2.client.registration.salesforce.client-id=${SALESFORCE_CLIENT_ID}
spring.security.oauth2.client.registration.salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}
spring.security.oauth2.client.registration.salesforce.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.salesforce.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.salesforce.scope=api,refresh_token

spring.security.oauth2.client.registration.salesforce.client-authentication-method=client_secret_post

spring.security.oauth2.client.provider.salesforce.authorization-uri=https://login.salesforce.com/services/oauth2/authorize
spring.security.oauth2.client.provider.salesforce.token-uri=https://login.salesforce.com/services/oauth2/token

salesforce.instance-url=https://java-momentum-86812.my.salesforce.com
salesforce.api-version=v67.0

spring.security.oauth2.client.provider.salesforce.user-info-uri=https://login.salesforce.com/services/oauth2/userinfo
spring.security.oauth2.client.provider.salesforce.user-name-attribute=sub

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE